import os

def advanced_report_generator(content: str, title: str = "Sili Neural Report", format: str = "markdown"):
    """Compiles research results into professional documents (PDF or Markdown)."""
    report_path = f"reports/{title.replace(' ', '_').lower()}.md"
    os.makedirs("reports", exist_ok=True)
    
    with open(report_path, "w") as f:
        f.write(f"# {title}\n\nGenerated by Sili V10 Neural Singularity\n\n{content}")
        
    return f"Professional {format} report generated at {report_path}"
